### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by kskenyon** [Airthings/wave-reader#13]
sudo python3 read_wave.py 2930029112 60
Traceback (most recent call last):
  File "read_wave.py", line 168, in <module>
    _main()
  File "read_wave.py", line 161, in _main
    current_values = wave.read()
  File "read_wave.py", line 89, in read
    rawdata = self._datetime_char.read()
AttributeError: 'NoneType' object has no attribute 'read'

What's missing?

**Comment by kbahey** [comment]
I am getting the same error on a 2930 device, with both the read_wave.py and read_wave2.py

What was the solution that caused this issue to be set to Closed?
