### ISSUE TITLE
Wave Plus Serial 293x is supported?

### ISSUE THREAD

**Issue by zack4m** [Airthings/wave-reader#15]
I bought a Wave Plus hoping I can use this project but upon trying both read_wave.py and read_wave2.py I cannot get the values. read_wave.py shows either BTLEDisconnectedError either name 'p' is not defined. read_wave2.py with SN shows BTLEDisconnectedError. Is my device supported by this library? I can tweak the code to get the values from Wave Plus?

**Comment by mnaz** [comment]
The read_wave2.py script worked fine for both of my devices. Did you check that things are working with the phone app? Maybe you could provide more detail on what device you are running the script and the steps you took to debug.
