### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by lasseklein** [Airthings/wave-reader#4]
Any thoughts on why I get these error messages after following the guide?

from: can't read /var/mail/bluepy.btle
import-im6.q16: unable to open X server `' @ error/import.c/ImportImageCommand/358.
from: can't read /var/mail/datetime
import-im6.q16: unable to open X server `' @ error/import.c/ImportImageCommand/358.
import-im6.q16: unable to open X server `' @ error/import.c/ImportImageCommand/358.
import-im6.q16: unable to open X server `' @ error/import.c/ImportImageCommand/358.
./read_wave.py: 40: ./read_wave.py: Syntax error: word unexpected (expecting ")")

**Comment by orjangj** [comment]
Never seen this kind of error. It seems like there's a syntax error in read_wave.py on line 40, but this shouldn't be a problem unless you've modified the script in some way?
