### ISSUE TITLE
Python 3?

### ISSUE THREAD

**Issue by buldre** [Airthings/wave-reader#8]
Will it work in Python 3?

**Comment by orjangj** [comment]
I haven't tested it with Python3, but I think it should work as long as you modify the print statements to be Python3 compliant. E.g. `print "something"` to `print("something")`.

**Comment by buldre** [comment]
Thanks! Good to know before I buy and try!

**Comment by orjangj** [comment]
Just a note:

If you plan on buying a 2nd generation Wave product, then read_wave.py will not work.
However, I can upload a script for that product if you'd like.

**Comment by buldre** [comment]
Hi,

Yes, please! And thanks!

Will you be able to test against a 2nd gen Wave? And I assume you use Python 3 now?

**Comment by orjangj** [comment]
I've uploaded read_wave2.py for reading sensor data from a 2nd Generation Wave. I've also modified the scripts to be both py2 and py3 compatible. See updated readme.

**Comment by orjangj** [comment]
I'll close this issue now that the repo provides the sufficient support for interfacing both 1st and 2nd Gen Wave devices. If you discover any issues, then don't hesitate to create a new issue.

**Comment by buldre** [comment]
Tusen takk!

Sendt fra min iPhone
